# -*- coding: utf-8 -*-
from . import models
from . import res_partner
from . import report_psi
from . import product_pricelist
from . import product_pricelist_item
from . import purchase_order
from . import product_template
from . import report_refe
from . import res_company
from . import calculo_comisiones
from . import bono_comisiones
from . import porcentaje_comisiones
from . import bono_detalle
from . import bono_calculo
from . import report_comisiones
from . import report_pago_comisiones
from . import report_macro90
from . import sale_order
from . import sale_order_line
from . import calculo_comisiones_tienda
#from . import crea_funcion
from . import purchase_order_line
from . import product_brand
from . import mail_channel
from . import users_pricelist
from . import pos_session
from . import estados_wms
from . import product_pricelist_item_sellers
#from . import revision_pedidos